## ALTER 

객체의 수정을 위해 사용

생성된 테이블의 속성과 속성에 관한 제약, 그리고 기본키 및 외래키를 변경한다

<br/>

```sql
조건 : 이전에 만든 TEST5 테이블 이용 

-- 테이블 생성 
CREATE TABLE TEST_COPY
AS SELECT * FROM TEST5;

SELECT * FROM TEST_COPY;

-- 칼럼 추가
ALTER TABLE TEST_COPY
ADD CUS_ROOM VARCHAR2(20);

SELECT * FROM TEST_COPY;

--기본 값 지정 가능
ALTER TABLE TEST_COPY
ADD MAS_ROOM VARCHAR2(20) DEFAULT '부재중';

SELECT * FROM TEST_COPY;

-- 컬럼 수정
ALTER TABLE TEST_COPY
MODIFY MYROOM_NAME VARCHAR2(25)
MODIFY MYROOM_NAME2 VARCHAR2(25)
MODIFY MAS_ROOM DEFAULT '대기중';

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT, COLUMN_ID, COMMENTS
FROM USER_TAB_COLUMNS
JOIN USER_COL_COMMENTS USING(TABLE_NAME, COLUMN_NAME)
WHERE TABLE_NAME = 'TEST_COPY';
-- 수정된 값, 크기 확인 가능

-- 컬럼 삭제
ALTER TABLE TEST_COPY
DROP COLUMN CUS_ROOM;

SELECT * FROM TEST_COPY;
-- 컬럼은 모두 삭제 불가능. 최소 테이블에 1개 이상의 컬럼이 남아있어야 함. 따라서
-- 모든 컬럼을 삭제하려 하면 오류 발생함

-- 제약조건이 있는 컬럼 삭제

-- 제약조건 확인
SELECT * 
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'TEST_COPY';

-- 제약조건 컬럼 삭제
CREATE TABLE TEST6(
    PK NUMBER PRIMARY KEY,
    FK NUMBER REFERENCES TEST6
);

-- 오류 발생 -> 제약조건이 설정된 컬럼은 삭제 불가능 -> 
-- CASCADE CONSTRAINTS 옵션 이용해 삭제
ALTER TABLE TEST6
DROP COLUMN PK CASCADE CONSTRAINTS;

-- 제약조건 추가, 삭제

-- 먼저 사용할 TEST_COPY 테이블의 제약조건과 행들을 확인한다.
SELECT * 
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'TEST_COPY';

SELECT * FROM TEST_COPY;

-- 제약조건 추가
ALTER TABLE TEST_COPY
ADD CONSTRAINT PRI_KEY PRIMARY KEY(MYROOM);

ALTER TABLE TEST_COPY
ADD CONSTRAINT UNI_MY UNIQUE(MYROOM_NAME);

ALTER TABLE TEST_COPY
MODIFY MYROOM CONSTRAINT MY_NOTNULL NOT NULL;

-- 다시 제약조건을 확인하면 제약조건이 추가되 있음을 알 수 있다.

-- 컬럼, 제약조건, 테이블 이름 변경

-- 컬럼 이름 변경
ALTER TABLE TEST_COPY
RENAME COLUMN MYROOM
TO ROOM_NO;

SELECT * FROM TEST_COPY;

- 제약조건 확인
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TEST_COPY';

-- 제약조건 수정
ALTER TABLE TEST_COPY
RENAME CONSTRAINT SYS_C007246 TO ROON_NO_NOTNULL;

-- 테이블명 변경(RENAME [테이블명] TO 변경명)
ALTER TABLE TEST_COPY 
RENAME TO TEST_COPY_TMP;

ALTER TABLE TEST_COPY_TMP
RENAME TO TEST_COPY;

SELECT * FROM TEST_COPY;
 --앞과 뒤로 TMP(임시), BAK(백업)을 붙여 테이블의 용도를 나타낸다.

-- DROP TABLE TEST_COPY CASCADE CONSTRAINT; -- 제약조건을 포함해서 테이블을 삭제
```
